import {
  REACT_APP_API_URL,
  REACT_APP_CLOUDINARY_CLOUD_NAME,
  REACT_APP_CLOUDINARY_UPLOAD_PRESET_USERS,
} from '@env'

export const API_URL = REACT_APP_API_URL
export const CLOUDINARY_CLOUD_NAME = REACT_APP_CLOUDINARY_CLOUD_NAME
export const CLOUDINARY_UPLOAD_PRESET_USERS = REACT_APP_CLOUDINARY_UPLOAD_PRESET_USERS
